### ISSUE TITLE
Game won't launch after the update

### ISSUE THREAD

**Issue by MeatMorning** [Sylkadi/ProcLimiter#1]
Check line at the bottom of log file
[Error  : Unity Log] KeyNotFoundException: The given key was not present in the dictionary.

[LogOutput.log](https://github.com/Sylkadi/ProcLimiter/files/8929903/LogOutput.log)

**Comment by Sylkadi** [comment]
Sorry for the late reply(only just saw this now), it's that some other mod(s) are changing the compiled version of the games code which then 'can' mess up my code. The mod that's causing this problem is Risky Mod. I'll try to fix the problem when I get the time for it(I have work).

**Comment by Sylkadi** [comment]
Should work properly now.
